
export const CUSTOMER_FETCH_ONE_SUCCESS = 'CUSTOMER_FETCH_ONE_SUCCESS';
export const CUSTOMER_FETCH_ALL_SUCCESS = 'CUSTOMER_FETCH_ALL_SUCCESS';
export const CUSTOMER_FETCH_SUCCESS = 'CUSTOMER_FETCH_SUCCESS';
export const CUSTOMER_CREATE_SUCCESS = 'CUSTOMER_CREATE_SUCCESS';
export const CUSTOMER_UPDATE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_DELETE_SUCCESS = 'CUSTOMER_DELETE_SUCCESS';